<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Search polls_options for &quot;<?php echo $question; ?>&quot;</h1>
    <p><?php echo $this->tag::linkTo(["polls_options/" . $poll_id . "/new", "Create polls_options"]) ?></p>
</div>

<?php echo $this->getContent() ?>

<?php echo $this->flash->output() ?>

<form action="/polls_options/search" class="form-horizontal" method="get">
    <div class="form-group">
        <label for="fieldId" class="col-sm-2 control-label">Id</label>
        <div class="col-sm-10">
            <?php echo $this->tag::textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldName" class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10">
            <?php echo $this->tag::textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldNumberVotes" class="col-sm-2 control-label">Number Of Votes</label>
        <div class="col-sm-10">
            <?php echo $this->tag::textField(["number_votes", "type" => "number", "class" => "form-control", "id" => "fieldNumberVotes"]) ?>
        </div>
    </div>


    <?php echo $this->tag::hiddenField(["poll_id", "type" => "number", "class" => "form-control", "id" => "fieldPollId"]) ?>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag::submitButton(["Search", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
