<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag::linkTo(["/polls_options/" . $poll_id, "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag::linkTo(["/polls_options/" . $poll_id . "/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result for &quot;<?php echo $question; ?>&quot;</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Name</th>
            <th>Number Of Votes</th>
            <th>Poll</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->getItems() as $polls_option): ?>
            <tr>
                <td><?php echo $polls_option['id'] ?></td>
            <td><?php echo $polls_option['name'] ?></td>
            <td><?php echo $polls_option['number_votes'] ?></td>
            <td><?php echo $polls_option['poll_id'] ?></td>

                <td><?php echo $this->tag::linkTo(["polls_options/edit/" . $polls_option['id'], "Edit"]); ?></td>
                <td><?php echo $this->tag::linkTo(["polls_options/delete/" . $polls_option['id'], "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->getCurrent(), "/", $page->getTotalItems() ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag::linkTo(["polls_options/search", "First", 'class' => 'page-link', 'id' => 'first']) ?></li>
                <li><?php echo $this->tag::linkTo(["polls_options/search?page=" . $page->getPrevious(), "Previous", 'class' => 'page-link', 'id' => 'previous']) ?></li>
                <li><?php echo $this->tag::linkTo(["polls_options/search?page=" . $page->getNext(), "Next", 'class' => 'page-link', 'id' => 'next']) ?></li>
                <li><?php echo $this->tag::linkTo(["polls_options/search?page=" . $page->getLast(), "Last", 'class' => 'page-link', 'id' => 'last']) ?></li>
            </ul>
        </nav>
    </div>
</div>
