<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Search polls</h1>
</div>

<?php echo $this->getContent() ?>

<?php echo $this->flash->output() ?>

<form action="/polls/search" class="form-horizontal" method="get">
    <div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldQuestion" class="col-sm-2 control-label">Question</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(["question", "size" => 30, "class" => "form-control", "id" => "fieldQuestion"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag::submitButton(["Search", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
