<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["/polls", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Create polls</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="/polls/create" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldQuestion" class="col-sm-2 control-label">Question</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["question", "size" => 30, "class" => "form-control", "id" => "fieldQuestion"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
