<?php
/**
 * @var Polls $poll
 * @var Php $this
 */

use Phalcon\Mvc\View\Engine\Php;

(new \Phalcon\Debug())->listen();
?>

<div class="page-header">
    <h1>View poll</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4"><?php echo $poll->question; ?></h1>

        <div class="container">
            <?php foreach ($options as $option) : ?>
                <div class="row">
                    <div class="col-1">
                        <?php echo $option->name; ?>
                    </div>
                    <div class="col-1">
                        <span class="badge badge-primary"><?php echo $option->number_votes; ?></span>
                    </div>
                    <div class="col-10">
                        <?php echo $this->tag::linkTo(["/polls_options/vote/" . $option->id, "Vote"]); ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <p><?php echo $this->tag::linkTo(["/polls/edit/" . $poll->id, "Edit"]); ?> |
            <?php echo $this->tag::linkTo(["/polls/delete/" . $poll->id, "Delete"]); ?> |
            <?php echo $this->tag::linkTo(["/polls_options/search?poll_id=" . $poll->id, "Manage options"]); ?></p>
    </div>
</div>
