<?php
/**
 * @var Polls $poll
 * @var Php $this
 */

use Phalcon\Mvc\View\Engine\Php;

(new \Phalcon\Debug())->listen();
?>

<!--<nav class="navbar navbar-default">-->
<!--    <div class="container-fluid">-->
<!--        <div class="navbar-header">-->
<!--            <a class="navbar-brand" href="#">Polls</a>-->
<!--        </div>-->
<!--        <ul class="nav navbar-nav">-->
<!--            <li class="nav-item active">--><?php //echo $this->tag::linkTo(['href'=>"/", 'text'=>"Back", 'class'=>'nav-link']) ?><!--</li>-->
<!--            <li class="nav-item">--><?php //echo $this->tag::linkTo(["/polls", "Search"]) ?><!--</li>-->
<!--        </ul>-->
<!--    </div>-->
<!--</nav>-->

<div class="page-header">
	<h1>View poll</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4"><?php echo $poll->question; ?></h1>
        <p class="lead">Number of votes: 0</p>
        <p><?php echo $this->tag::linkTo(["/polls/edit/" . $poll->id, "Edit"]); ?> |
            <?php echo $this->tag::linkTo(["/polls/delete/" . $poll->id, "Delete"]); ?></p>
    </div>
</div>
